### ISSUE TITLE
Unable to boot v5.4 with rt patch

### ISSUE THREAD

**Issue by dozack** [RobertCNelson/armv7-lpae-multiplatform#5]
Hello, I am unable to boot linux kernel 5.4 with rt patch on STM32MP157-DK2 development board.
# Steps to reproduce

- checkout v5.4.x branch
- select  `toolchain="gcc_arm_gnueabihf_10"` in version.sh
- uncomment `rt` in patch.sh
## menuconfig
- change kernel mode to PREEMPT_RT
- set timer frequency to 1000 Hz

# Boot log

```
U-Boot 2020.10 (Jan 07 2021 - 19:01:09 +0100)

CPU: STM32MP157CAC Rev.B
Model: STMicroelectronics STM32MP157C-DK2 Discovery Board
Board: stm32mp1 in basic mode (st,stm32mp157c-dk2)
Board: MB1272 Var2.0 Rev.C-01
DRAM:  512 MiB
Clocks:
- MPU : 650 MHz
- MCU : 208.878 MHz
- AXI : 266.500 MHz
- PER : 24 MHz
- DDR : 533 MHz
WDT:   Started with servicing (32s timeout)
NAND:  0 MiB
MMC:   STM32 SD/MMC: 0
Loading Environment from MMC... OK
In:    serial
Out:   serial
Err:   serial
Net:   eth0: ethernet@5800a000
starting USB...
Bus usbh-ehci@5800d000: USB EHCI 1.00
scanning bus usbh-ehci@5800d000 for devices... 2 USB Device(s) found
       scanning usb for storage devices... 0 Storage Device(s) found
Hit any key to stop autoboot:  0 
Boot over mmc0!
switch to partitions #0, OK
mmc0 is current device
Scanning mmc 0:4...
Found /boot/extlinux/extlinux.conf
Retrieving file: /boot/extlinux/extlinux.conf
276 bytes read in 31 ms (7.8 KiB/s)
1:	Linux 5.4.84-armv7-lpae-x40
Retrieving file: /boot/vmlinuz-5.4.84-armv7-lpae-x40
10408448 bytes read in 469 ms (21.2 MiB/s)
append: console=ttySTM0,115200 root=/dev/mmcblk0p4 ro rootfstype=ext4 rootwait
Retrieving file: /boot/dtbs/5.4.84-armv7-lpae-x40/stm32mp157c-dk2.dtb
70187 bytes read in 36 ms (1.9 MiB/s)
## Flattened Device Tree blob at c4000000
Booting using the fdt blob at 0xc4000000
Loading Device Tree to cffeb000, end cffff22a ... OK

Starting kernel ...
```

Booting does not continue and board is reset every 32 seconds by watchodog. Could you please provide any suggestion how to get any kernel running with rt patch? I do not insist on using 5.4, but i need rt.
Thanks

**Comment by dozack** [comment]
Btw i followed instructions for preparing bootloader, distro and SD card [there](https://www.digikey.com/eewiki/display/linuxonarm/STM32MP1).

**Comment by RobertCNelson** [comment]
@dozack this looks like one of the fun bugs i've been chasing down, thumb2+gcc10, i'm seeing the same issue on an imx6 based target..

**Comment by dozack** [comment]
@RobertCNelson  shall i try building with older gcc?

**Comment by dozack** [comment]
Compiling with `toolchain="gcc_arm_gnueabihf_8"` solved my problem. Thanks for pinpointing.
